### PR TITLE
Add gpg signing support

### PR DESCRIPTION
**Pull request by SuperBo**
Add preliminary support for gpg signing commit. Now only support create commit with signing.

### CODE REVIEW

**Comment by calops** [comment]
This adds `libgpgme.so` as a dependency, correct? If so, maybe the README should be updated?

**Comment by SuperBo** [comment]
@calops , yes, but it adds libgpgme.so as a lazy dependency. If you don't install and don't use gpg siging, no problem is raised.

**Comment by calops** [comment]
The problem is that if do use gpg signing, the plugin stops being able to commit all of a sudden, without having to enable anything in its configuration. That doesn't make it a lazy dependency in my opinion.

**Comment by SuperBo** [comment]
Thank you @calops, and sorry for disturbing your workflow 🙇. I updated README, let me know if I missed anything else!

**Comment by calops** [comment]
No worries 👍 
It wasn't hard to figure out the issue anyway since the error message mentions the dependency. But maybe it would be better for the plugin itself to detect if that dependency is present and then prompt a proper warning to the user if they're using gpg signing?

**Comment by SuperBo** [comment]
@calops, Sure, I will revise all error logging and warning. Need to finish some other features first.

**Pull request merged**
